spring
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: test1
  application:
    name: microservicecloud-config-test