spring:
  profiles:
    active:
    - dev   
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:       
    hostname: eureka7001.com
  client:
    fetch-registry: false          #false表示不向注册中心注册自己
    register-with-eureka: false     #false表示自己端就是注册中心 只维护实例，
    serviceUrl:
      #设置与Eureka server 交互的地址查询服务和注册服务
      #单机http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:       
    hostname: eureka7001.com
  client:
    fetch-registry: false          #false表示不向注册中心注册自己
    register-with-eureka: false     #false表示自己端就是注册中心 只维护实例，
    serviceUrl:
      #设置与Eureka server 交互的地址查询服务和注册服务
      #单机http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/   
